platform:
  - x64

install:

build_script:
  - compile_cl.bat
  - cd test
  - compile_cl.bat
  - cd ..\src\examples
  - compile_cl.bat
  - cd ..\..\

test_script:
  - build\main.exe -?
  - build\main.exe -w 512 -h 512 -n 100 -o citest.png
  - build\test.exe
  - build\test_double.exe
  - build\simple.exe
